/**
 * BD-17.7 - CORRECCION CHECKLIST AGENDA
 * Acceso directo y robusto al checklist de Etapa 1.1 y 2.1.
 */
const BD177_CONFIG=Object.freeze({fase:'BD-17.7',version:'db-17.7-checklist-fix',sheet:'AGENDA_CHECKLIST'});
function BD177_norm_(v){return String(v==null?'':v).trim();}
function BD177_up_(v){return BD177_norm_(v).toUpperCase();}
function BD178_fechaCliente_(v){if(!v)return '';if(Object.prototype.toString.call(v)==='[object Date]'){return Utilities.formatDate(v,Session.getScriptTimeZone()||'America/Lima','dd/MM/yyyy HH:mm:ss');}return BD177_norm_(v);}
function BD177_items_(e){if(Number(e)===1)return['Plan de Tesis/Trabajo Académico','Recibo derecho de Inscripción Plan de Tesis','Anexo 17 Solicitud','Anexo 18 Aceptación de asesoría','Autorización de uso de información o declaración jurada Anexo 33','En el caso de Trabajo Académico, evidenciar 2 años de experiencia posterior a la fecha de egreso con la Constancia de Trabajo y Reporte SUNARP'];if(Number(e)===2)return['Anexo 8 formato de Culminación de Asesoría','Anexo 27 Solicitud de titulación','Anexo 2 declaración jurada de antecedentes','Anexo 32 Declaración jurada de veracidad de la información','Recibos de pago derecho de titulación','Anexo 1','Libreta de notas','Certificado de estudios','Constancia de primera matrícula','Constancia de Egresado','Constancia de no adeudar bienes y servicios (pensiones)','Constancia de no adeudar libros a biblioteca','Fotografía en formato JPG'];return[];}
function BD177_sheet_(){var ss=BD5_abrirBase_();if(!ss)throw new Error('No se pudo abrir BD_TITULACION_RELACIONAL_V2.');var sh=ss.getSheetByName(BD177_CONFIG.sheet);if(!sh){sh=ss.insertSheet(BD177_CONFIG.sheet);sh.getRange(1,1,1,9).setValues([['ID','ID_EXPEDIENTE','CODIGO_TRAMITE','ETAPA','NUMERO','REQUISITO','MARCADO','USUARIO','MODIFICADO_EN']]);sh.setFrozenRows(1);}return sh;}
function BD177_expediente_(codigo){codigo=BD177_up_(codigo);var sh=BD5_tabla_('expedientes'),lr=sh.getLastRow(),lc=sh.getLastColumn();if(lr<2)return null;var v=sh.getRange(1,1,lr,lc).getValues(),h=v[0].map(BD177_up_),ic=h.indexOf('CODIGO_TRAMITE'),ii=h.indexOf('ID_EXPEDIENTE');if(ic<0||ii<0)throw new Error('EXPEDIENTES no contiene ID_EXPEDIENTE/CODIGO_TRAMITE.');for(var i=1;i<v.length;i++)if(BD177_up_(v[i][ic])===codigo)return{id:BD177_norm_(v[i][ii]),codigo:codigo};return null;}
function BD177_asegurar_(exp,etapa){var items=BD177_items_(etapa);if(!items.length)throw new Error('Etapa sin checklist configurado.');var sh=BD177_sheet_(),lr=sh.getLastRow(),v=lr>1?sh.getRange(2,1,lr-1,9).getValues():[],ex={};v.forEach(function(r){if(BD177_norm_(r[1])===exp.id&&Number(r[3])===Number(etapa))ex[Number(r[4])]=true;});var add=[],now=new Date();items.forEach(function(nom,i){var n=i+1;if(!ex[n])add.push(['AGC_'+exp.id.replace(/[^A-Za-z0-9]/g,'')+'_'+etapa+'_'+n,exp.id,exp.codigo,Number(etapa),n,nom,'NO','',now]);});if(add.length)sh.getRange(sh.getLastRow()+1,1,add.length,9).setValues(add);}
function BD177_OBTENER_CHECKLIST(codigo,etapa){try{var exp=BD177_expediente_(codigo);if(!exp)return{status:false,message:'No se encontró el expediente '+BD177_up_(codigo)+' en EXPEDIENTES.'};BD177_asegurar_(exp,etapa);var sh=BD177_sheet_(),lr=sh.getLastRow(),v=lr>1?sh.getRange(2,1,lr-1,9).getValues():[],req=[];v.forEach(function(r){if(BD177_norm_(r[1])===exp.id&&Number(r[3])===Number(etapa))req.push({numero:Number(r[4]),nombre:BD177_norm_(r[5]),marcado:BD177_up_(r[6])==='SI',usuario:BD177_norm_(r[7]),actualizado:BD178_fechaCliente_(r[8])});});req.sort(function(a,b){return a.numero-b.numero;});var m=req.filter(function(x){return x.marcado;}).length,t=req.length;return{status:true,expediente:exp.codigo,idExpediente:exp.id,etapa:Number(etapa),marcados:m,total:t,completo:t>0&&m===t,porcentaje:t?Math.round(m*100/t):0,requisitos:req};}catch(e){Logger.log('[BD-17.7] '+e.stack);return{status:false,message:e.message||String(e)};}}
function BD177_GUARDAR_CHECK(codigo,etapa,numero,marcado,usuario){try{var exp=BD177_expediente_(codigo);if(!exp)return{status:false,message:'No se encontró el expediente '+BD177_up_(codigo)+'.'};BD177_asegurar_(exp,etapa);var sh=BD177_sheet_(),lr=sh.getLastRow(),v=lr>1?sh.getRange(2,1,lr-1,9).getValues():[];for(var i=0;i<v.length;i++)if(BD177_norm_(v[i][1])===exp.id&&Number(v[i][3])===Number(etapa)&&Number(v[i][4])===Number(numero)){sh.getRange(i+2,7,1,3).setValues([[marcado?'SI':'NO',usuario||'',new Date()]]);return BD177_OBTENER_CHECKLIST(exp.codigo,etapa);}return{status:false,message:'No se encontró el requisito.'};}catch(e){Logger.log('[BD-17.7] '+e.stack);return{status:false,message:e.message||String(e)};}}
function BD177_REPARAR_CHECKLISTS(){var exps=REPO_RelacionalV5.listar('expedientes')||[],creados=0,errores=[];exps.forEach(function(e){[1,2].forEach(function(et){try{var sh=BD177_sheet_(),a=sh.getLastRow();BD177_asegurar_({id:BD177_norm_(e.ID_EXPEDIENTE),codigo:BD177_up_(e.CODIGO_TRAMITE)},et);creados+=Math.max(0,sh.getLastRow()-a);}catch(x){errores.push((e.CODIGO_TRAMITE||e.ID_EXPEDIENTE)+' E'+et+': '+x.message);}});});var o={status:errores.length===0,fase:BD177_CONFIG.fase,expedientes:exps.length,filasCreadas:creados,errores:errores};Logger.log(JSON.stringify(o,null,2));return o;}
function BD177_PROBAR_DIAGNOSTICO(){var exps=REPO_RelacionalV5.listar('expedientes')||[],fallas=[];exps.forEach(function(e){[1,2].forEach(function(et){var r=BD177_OBTENER_CHECKLIST(e.CODIGO_TRAMITE,et),esp=BD177_items_(et).length;if(!r.status||r.total!==esp)fallas.push({expediente:e.CODIGO_TRAMITE,etapa:et,total:r.total||0,esperado:esp,mensaje:r.message||''});});});var o={status:fallas.length===0,fase:BD177_CONFIG.fase,version:BD177_CONFIG.version,expedientes:exps.length,checklistEtapa1:6,checklistEtapa2:13,fallas:fallas};Logger.log(JSON.stringify(o,null,2));return o;}

